language: minimal

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install make

script:
 - make build

deploy:
  provider: releases
  api_key:
    secure: DQLIESM1VEnZwrZSai7yVyek3SXc2XT2PKcdJo86vInfWdJTJGJD6xqRsdgD8EweJhh4JAiZnK+1ERUQQ7mdFVOu8/TKnWN4Ym5YDcrhwiNc7QtOC1EPXFcenf143b4D6GWR+m3BPbp5uqgusYHojJUZ+FyYVXbtUgvvKdbz5cLvx0RpqeBJ5XWOCWsU5oM8aLiX2R2V/g5Te/LY+U+poJGV/s16rWumss7HKwSzsX2PuMp5ADvm2zUauORQ22LFzH4DlRMwwm/d64m+rgAaHke/aUiYpGKQRUCnIEn3Ty+ippCF1ngD+/iAj1puTk/I+hkA4VCvW1jb/SGQcSvKMtrQk4Ark87JzpguI39bqm/Kt3wK7XynuB7zBzdTSLu7UOqQvdxswP0CMNtLQNpQvQRjBviU9fzvuA3Y3Rz72EQQlfhE77ynWSSImkPeMZPhFlHukrjMTS/0rFoBCm1yCmNV6cmZmL5RdyvzcRq3rz/RxL25gmyE0VkhFL6MWIgK96Y55OKFpsKqImkzXjR09g9BQYVNUB4iN9pODWEMW/IhBgHsVkmvGfzMG04FslU/3jLoZZN6YUn8m9rDh75uY/3URUrTANNvblK07FQOcLCrVnPxpe/OHz6Be6y8i5BBnu3zw8/oQyUaQBU0N71xD2ZQmoY/GhXtmGZxqETHlmQ=
  file_glob: true
  file: release/*
  skip_clleanup: true
  on:
    tags: true
